### ISSUE TITLE
Not importing any list  mationed 19.4.2022

### ISSUE THREAD

**Issue by mpodhola** [pschonmann/turrisgreylist2mikrotik#1]
Hi 
After I push list on my Microtic router no  black-list was imported.

**Comment by pschonmann** [comment]
Problem is that source file is empty. I tried to write post on turris forum.
https://forum.turris.cz/t/greylist-latest-csv-data-nejsou-aktualni/17070
Probably bug in generation data file.

**Comment by pschonmann** [comment]
Fixed in effc621c1a7383323f66efcd7b8508818c1b1e2c 
List is back again.
